ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
# ZTE_MODIFY : added begin by liyibo 2013-6-18
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
# ZTE_MODIFY : added end by liyibo 2013-6-18
obj-$(CONFIG_MSMB_CAMERA) += msm_led_flash.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_trigger.o
obj-$(CONFIG_MSMB_CAMERA) += adp165_led_trigger.o
